Write a python program to create two matrices (read values from the user) and find the following

In [6]:
import numpy as np

In [14]:
a,b = map(int,input("Enter the number of rows and column : ").split(","))
matrix = []
for i in range(a):
    mat = []
    for j in range(b):
        mat.append(int(input(f"Enter ({i},{j}) : ")))
    matrix.append(mat)
print(matrix)

c,d = map(int,input("Enter the number of rows and column for II matrix : ").split(","))
matrix2 = []
for i in range(c):
    mat2 = []
    for j in range(d):
        mat2.append(int(input(f"Enter ({i},{j}) : ")))
    matrix2.append(mat2)
print(matrix2)

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]
[[1, 2], [3, 4], [5, 6]]


1. Dot Product

In [15]:
if(b==c):
    print("Dot product is : \n",np.dot(matrix,matrix2))

Dot product is : 
 [[22 28]
 [49 64]
 [67 88]]


2. Transpose

In [16]:
print("Transpose of matrix is : \n",np.transpose(matrix))

Transpose of matrix is : 
 [[1 4 6]
 [2 5 7]
 [3 6 8]]


3. Trace

In [17]:
print("Trace od the matrix is: ",np.trace(matrix))

Trace od the matrix is:  14


4. Rank

In [18]:
print("Rank of the matrix is: ",np.linalg.matrix_rank(matrix))

Rank of the matrix is:  2


5. Diterminant

In [19]:
print("Determinent of matrix is : ",np.linalg.det(matrix))

Determinent of matrix is :  -3.885780586188069e-15


6. Inverse

In [20]:
print("Inverse of the matrix: \n",np.linalg.inv(matrix))

Inverse of the matrix: 
 [[ 5.14697100e+14 -1.28674275e+15  7.72045650e+14]
 [-1.02939420e+15  2.57348550e+15 -1.54409130e+15]
 [ 5.14697100e+14 -1.28674275e+15  7.72045650e+14]]


7. Eigen Values and Eigen Vectors

In [26]:
val, vect = np.linalg.eig(matrix)
print(f"Eigen Values : \n{val}\n Eigen Vectors are : \n{vect}" )

Eigen Values : 
[ 1.50000000e+01 -1.00000000e+00  4.65763037e-17]
 Eigen Vectors are : 
[[ 2.49206599e-01  8.32050294e-01  4.08248290e-01]
 [ 5.69615084e-01 -4.59516133e-16 -8.16496581e-01]
 [ 7.83220740e-01 -5.54700196e-01  4.08248290e-01]]
